apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portal.fullname" . }}-keycloak-realm
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
data:
{{ (.Files.Glob "files/portal-realm.json").AsConfig | indent 2 }}
