apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}-mfe-hello
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: mfe-hello
spec:
  type: {{ .Values.service.mfeHello.type }}
  selector:
    {{- include "portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mfe-hello
  ports:
    - port: 80
      targetPort: 8080
      {{- if and (eq .Values.service.mfeHello.type "NodePort") .Values.service.mfeHello.nodePort }}
      nodePort: {{ .Values.service.mfeHello.nodePort }}
      {{- end }}
