apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}-mfe-home
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: mfe-home
spec:
  type: {{ .Values.service.mfeHome.type }}
  selector:
    {{- include "portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mfe-home
  ports:
    - port: 80
      targetPort: 8080
      {{- if and (eq .Values.service.mfeHome.type "NodePort") .Values.service.mfeHome.nodePort }}
      nodePort: {{ .Values.service.mfeHome.nodePort }}
      {{- end }}
